// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Crowdfunding.Database.Entities;

[Table("Account")]
public partial class Account
{
    [Key]
    [Column("ID")]
    public Guid Id { get; set; }

    [Column("UserID")]
    public Guid UserId { get; set; }

    [Required]
    [Column("Account")]
    [StringLength(50)]
    public string Account1 { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Accounts")]
    public virtual User User { get; set; }
}