// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Crowdfunding.Database.Entities;

[Table("ProjectImage")]
public partial class ProjectImage
{
    [Key]
    [Column("ID")]
    public Guid Id { get; set; }

    [Required]
    public string Img { get; set; }

    [Column("ProjectID")]
    public Guid ProjectId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateTime { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("ProjectImages")]
    public virtual Project Project { get; set; }
}