// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Crowdfunding.Database.Entities;

[Table("Project")]
public partial class Project
{
    [Key]
    [Column("ID")]
    public Guid Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("ProjectTypeID")]
    public Guid ProjectTypeId { get; set; }

    public string Cover { get; set; }

    public int TargetMoney { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpireTime { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    public string Detail { get; set; }

    [Column("UserID")]
    public Guid UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateTime { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdateTime { get; set; }

    public bool IsDelete { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("Project")]
    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    [InverseProperty("Project")]
    public virtual ICollection<InvestItem> InvestItems { get; set; } = new List<InvestItem>();

    [InverseProperty("Project")]
    public virtual ICollection<News> News { get; set; } = new List<News>();

    [InverseProperty("Project")]
    public virtual ICollection<ProjectImage> ProjectImages { get; set; } = new List<ProjectImage>();

    [ForeignKey("ProjectTypeId")]
    [InverseProperty("Projects")]
    public virtual ProjectType ProjectType { get; set; }

    [InverseProperty("Project")]
    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    [InverseProperty("Project")]
    public virtual ICollection<SuperComment> SuperComments { get; set; } = new List<SuperComment>();

    [ForeignKey("UserId")]
    [InverseProperty("Projects")]
    public virtual User User { get; set; }
}