// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Crowdfunding.Database.Entities;

[Table("SuperComment")]
public partial class SuperComment
{
    [Key]
    [Column("ID")]
    public Guid Id { get; set; }

    [Required]
    public string Message { get; set; }

    public int Donate { get; set; }

    [Column("UserID")]
    public Guid UserId { get; set; }

    [Column("ProjectID")]
    public Guid ProjectId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateTime { get; set; }

    [ForeignKey("ProjectId")]
    [InverseProperty("SuperComments")]
    public virtual Project Project { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("SuperComments")]
    public virtual User User { get; set; }
}